Models/AulaViewModel.cs
using System;

namespace ProjetoN2.Models
{
    public class AulaViewModel : SuperViewModel
    {
        public DateTime Data { get; set; }
        public int MateriaId { get; set; }
        public string MateriaNome { get; set; }
        public int TurmaId { get; set; }
        public string TurmaNome { get; set; }
        public int SalaId { get; set; }
    }
}

Controllers/AulaController.cs
using ProjetoN2.DAO;
using ProjetoN2.Models;

namespace ProjetoN2.Controllers
{
    public class AulaController : SuperController<AulaViewModel>
    {
        public AulaController()
        {
            DAO = new AulaDAO();
        }

        protected override void ValidateModel(AulaViewModel model)
        {
            ModelState.Clear();

            if(((AulaDAO)DAO).materiaDAO.SelectById(model.MateriaId) == null)
            {
                ModelState.AddModelError("MateriaId", "Nenhuma matéria existe");
            }

            if(((AulaDAO)DAO).turmaDAO.SelectById(model.TurmaId) == null)
            {
                ModelState.AddModelError("TurmaId", "Nenhuma turma existe");
            }

            if(((AulaDAO)DAO).salaDAO.SelectById(model.SalaId) == null)
            {
                ModelState.AddModelError("SalaId", "Nenhuma sala existe");
            }
        }

        protected override void PrepareView()
        {
            ViewBag.Materias = ((AulaDAO)DAO).materiaDAO.SelectAll();
            ViewBag.Turmas = ((AulaDAO)DAO).turmaDAO.SelectAll();
            ViewBag.Salas = ((AulaDAO)DAO).salaDAO.SelectAll();
        }
    }
}

Views/Aula/Form.cshtml
@model ProjetoN2.Models.AulaViewModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <form class="form-horizontal" asp-action="Save" asp-controller="Aula">
        <input type="hidden" asp-for="Id">

        <label asp-for="MateriaId"></label>
        <select class="form-control" asp-for="MateriaId" asp-items='@(new SelectList(ViewBag.Materias, "Id", "Nome"))'></select>
        <span class="text-danger" asp-validation-for="MateriaId"></span>
        <br>

        <label asp-for="TurmaId"></label>
        <select class="form-control" asp-for="TurmaId" asp-items='@(new SelectList(ViewBag.Turmas, "Id", "Nome"))'></select>
        <span class="text-danger" asp-validation-for="TurmaId"></span>
        <br>

        <label asp-for="SalaId"></label>
        <select class="form-control" asp-for="SalaId" asp-items='@(new SelectList(ViewBag.Salas, "Id", "Id"))'></select>
        <span class="text-danger" asp-validation-for="SalaId"></span>
        <br>
        
        <button class="btn btn-outline-dark">Salvar</button>
    </form>
</div>

Views/Aula/Index.cshtml
@model IEnumerable<ProjetoN2.Models.AulaViewModel>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h3>Aulas</h3>
    <a class="btn btn-striped btn-outline-dark" href="/aula/Create">Adicionar</a>
    <br><br><br>

    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Id</th>
                <th>Turma</th>
                <th>Materia</th>
                <th>Sala Nº</th>
                <th>Data</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var aula in Model)
            {
                <tr>
                    <td>@aula.Id</td>
                    <td>@aula.TurmaNome</td>
                    <td>@aula.MateriaNome</td>
                    <td>@aula.SalaId</td>
                    <td>@aula.Data.ToString("d")</td>
                    <td>
                        <a href="/aula/Update?id=@aula.Id" class="btn btn-outline-warning">Atualizar</a>
                        <a href="/aula/Delete?id=@aula.Id" class="btn btn-outline-danger">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>