Models/AlunoViewModel.cs
namespace ProjetoN2.Models
{
    public class AlunoViewModel : SuperViewModel
    {
        public string Nome { get; set; }
        public int TurmaId { get; set; }
        public string TurmaNome { get; set; }
    }
}

Controllers/AlunoController.cs
using ProjetoN2.DAO;
using ProjetoN2.Models;

namespace ProjetoN2.Controllers
{
    public class AlunoController : SuperController<AlunoViewModel>
    {
        public AlunoController()
        {
            DAO = new AlunoDAO();
        }

        protected override void ValidateModel(AlunoViewModel model)
        {
            ModelState.Clear();

            if(string.IsNullOrEmpty(model.Nome))
            {
                ModelState.AddModelError("Nome", "Nome não pode ser vazio.");
            }

            if(((AlunoDAO)DAO).turmaDAO.SelectById(model.TurmaId) == null)
            {
                ModelState.AddModelError("TurmaId", "Nenhuma turma existe.");
            }
        }

        protected override void PrepareView()
        {
            ViewBag.Turmas = ((AlunoDAO)DAO).turmaDAO.SelectAll();
        }
    }
}

Views/Aluno/Form.cshtml
@model ProjetoN2.Models.AlunoViewModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <form class="form-horizontal" asp-action="Save" asp-controller="Aluno">
        <input type="hidden" asp-for="Id">

        <label asp-for="Nome"></label>
        <input class="form-control" asp-for="Nome">
        <span class="text-danger" asp-validation-for="Nome"></span>
        <br>

        <label asp-for="TurmaId"></label>
        <select class="form-control" asp-for="TurmaId" asp-items='@(new SelectList(ViewBag.Turmas, "Id", "Nome"))'></select>
        <span class="text-danger" asp-validation-for="TurmaId"></span>
        <br>
        
        <button class="btn btn-outline-dark">Salvar</button>
    </form>
</div>

Views/Aluno/Index.cshtml
@model IEnumerable<ProjetoN2.Models.AlunoViewModel>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h3>Alunos</h3>
    <a class="btn btn-striped btn-outline-dark" href="/aluno/Create">Adicionar</a>
    <br><br><br>

    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>Turma</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var aluno in Model)
            {
                <tr>
                    <td>@aluno.Id</td>
                    <td>@aluno.Nome</td>
                    <td>@aluno.TurmaNome</td>
                    <td>
                        <a href="/aluno/Update?id=@aluno.Id" class="btn btn-outline-warning">Atualizar</a>
                        <a href="/aluno/Delete?id=@aluno.Id" class="btn btn-outline-danger">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>