Models/SalaViewModel.cs
namespace ProjetoN2.Models
{
    public class SalaViewModel : SuperViewModel
    {
        public int Capacidade { get; set; }
    }
}

Controllers/SalaController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoN2.DAO;
using ProjetoN2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjetoN2.Controllers
{
    public class SalaController : SuperController<SalaViewModel>
    {
        public SalaController()
        {
            DAO = new SalaDAO();
        }
        protected override void ValidateModel(SalaViewModel model)
        {
            ModelState.Clear();

            if (model.Capacidade < 5)
            {
                ModelState.AddModelError("Capacidade", "Capacidade não pode ser menor que 5.");
            }
        }
    }
}

Views/Sala/Form.cshtml
@model ProjetoN2.Models.SalaViewModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <form class="form-horizontal" asp-action="Save" asp-controller="Sala">
        <input type="hidden" asp-for="Id">
        <label asp-for="Capacidade"></label>
        <input class="form-control" asp-for="Capacidade">
        <span class="text-danger" asp-validation-for="Capacidade"></span>
        <br>

        <button class="btn btn-outline-dark">Salvar</button>
    </form>
</div>

Views/Sala/Index.cshtml
@model IEnumerable<ProjetoN2.Models.SalaViewModel>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h3>Salas</h3>
    <a class="btn btn-striped btn-outline-dark" href="/Sala/Create">Adicionar</a>
    <br><br><br>

    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Id</th>
                <th>Capacidade</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var sala in Model)
            {
                <tr>
                    <td>@sala.Id</td>
                    <td>@sala.Capacidade</td>
                    <td>
                        <a href="/Sala/Update?id=@sala.Id" class="btn btn-outline-warning">Atualizar</a>
                        <a href="/Sala/Delete?id=@sala.Id" class="btn btn-outline-danger">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>