Models/CursoViewModel.cs
using ProjetoN2.Enums;

namespace ProjetoN2.Models
{
    public class CursoViewModel : SuperViewModel
    {
        public string Nome { get; set; }
        public EPeriodo Periodo { get; set; }
    }
}

Controllers/CursoController.cs
using ProjetoN2.DAO;
using ProjetoN2.Models;

namespace ProjetoN2.Controllers
{
    public class CursoController : SuperController<CursoViewModel>
    {
        public CursoController()
        {
            DAO = new CursoDAO();
        }
        protected override void ValidateModel(CursoViewModel model)
        {
            ModelState.Clear();

            if(string.IsNullOrEmpty(model.Nome))
            {
                ModelState.AddModelError("Nome", "Nome não pode ser vazio.");
            }
        }
    }
}

Views/Curso/Form.cshtml
@model ProjetoN2.Models.CursoViewModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <form class="form-horizontal" asp-action="Save" asp-controller="Curso">
        <input type="hidden" asp-for="Id">
        <label asp-for="Nome"></label>
        <input class="form-control" asp-for="Nome">
        <span class="text-danger" asp-validation-for="Nome"></span>
        <br>
        <label asp-for="Periodo"></label>
        <select class="form-control" asp-for="Periodo" asp-items="Html.GetEnumSelectList<ProjetoN2.Enums.EPeriodo>()"></select>
        <span class="text-danger" asp-validation-for="Nome"></span>
        <br>

        <button class="btn btn-outline-dark">Salvar</button>
    </form>
</div>

Views/Curso/Index.cshtml
@model IEnumerable<ProjetoN2.Models.CursoViewModel>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h3>Cursos</h3>
    <a class="btn btn-striped btn-outline-dark" href="/Curso/Create">Adicionar</a>
    <br><br><br>

    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>Período</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var curso in Model)
            {
                <tr>
                    <td>@curso.Id</td>
                    <td>@curso.Nome</td>
                    <td>@curso.Periodo</td>
                    <td>
                        <a href="/curso/Update?id=@curso.Id" class="btn btn-outline-warning">Atualizar</a>
                        <a href="/curso/Delete?id=@curso.Id" class="btn btn-outline-danger">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>